# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0
  aws-cli: circleci/aws-cli@2.0.3 
  
jobs:
  linting_blue:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "blue/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies for blue deployment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd blue
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            
      # run lint!
      - run:
          name: run lint for blue deployment
          command: |
            . venv/bin/activate
            cd blue
            make lint 
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "blue/requirements.txt" }}
          
  linting_green:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "green/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies for blue deployment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd green
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            
      # run lint!
      - run:
          name: run lint for green deployment
          command: |
            . venv/bin/activate
            cd green
            make lint 
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "green/requirements.txt" }}

      
            
  build-and-push-docker-blue:
    docker:
      - image: circleci/python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
     
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
          
      - run:
          name: build docker image for blue deployment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd blue
            make install
            docker build --tag=blue_capstone_api .
      
      - run:
          name: upload docker image for blue deployment to cloudhub
          command: |
            . venv/bin/activate
            cd blue
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            docker tag blue_capstone_api:latest panosdoxos/blue_capstone_api:latest
            docker push panosdoxos/blue_capstone_api:latest
            
  build-and-push-docker-green:
    docker:
      - image: circleci/python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
     
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
          
      - run:
          name: build docker image for green deployment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd green
            make install
            docker build --tag=green_capstone_api .
      
      - run:
          name: upload docker image for green deployment to cloudhub
          command: |
            . venv/bin/activate
            cd green
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            docker tag green_capstone_api:latest panosdoxos/green_capstone_api:latest
            docker push panosdoxos/green_capstone_api:latest
      
  create-cluster:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - run:
          name: install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version

      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
    
    
  test-cluster:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install:
          kubectl-version: v1.22.0
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster
  
  deploy-blue:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - kubernetes/install:
          kubectl-version: v1.22.0
      - run:
          name: Deploy blue deployment in cluster
          command: |
            cd blue
            chmod +x run_kubernetes.sh
            ./run_kubernetes.sh
      - run:
          name: Test blue deployment 
          command: |
            sleep 120 && kubectl get all
            
  deploy-green:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - kubernetes/install:
          kubectl-version: v1.22.0
      - run:
          name: Deploy green deployment in cluster
          command: |
            cd green
            chmod +x run_kubernetes.sh
            ./run_kubernetes.sh
      - run:
          name: Test green deployment 
          command: |
            sleep 120 && kubectl get all
            
  create-deployment-blue:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: blue/kubernetes_deployments/deployment.json
          resource-name: deployment/blue
  create-service-blue:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: blue/kubernetes_deployments/service.json
          resource-name: service/bluegreenlb
          
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - linting_blue
      - linting_green
      - build-and-push-docker-blue:
          requires:
            - linting_blue
      - build-and-push-docker-green:
          requires:
            - linting_green
    #   - create-cluster:
    #       cluster-name: my-eks
    #       requires:
    #         - build-and-push-docker
    #   - test-cluster:
    #       cluster-name: my-eks
    #       requires:
    #         - create-cluster
    #   - deploy-blue:
    #       requires:
    #         - build-and-push-docker-blue
    #   - deploy-green:
    #       requires:
    #         - build-and-push-docker-green
      - create-deployment-blue:
          cluster-name: my-eks
          requires:
            - build-and-push-docker-blue
      - create-service-blue:
          cluster-name: my-eks
          requires:
            - create-deployment-blue
    
    